name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: List contents of .next directory
        run: ls -la ./.next  # Vérifie le contenu du répertoire de sortie

      - name: Create .nojekyll file
        run: echo "" > ./.next/.nojekyll  # Crée un fichier vide .nojekyll dans le répertoire de publication

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.next  # Utilise le répertoire .next pour le déploiement
